// Real, verified logo files for hiring-partner companies that Simple Icons
// (see BrandIcon.tsx) doesn't cover - mostly wordmark logos, sourced from
// each company's Wikipedia/Wikimedia Commons infobox image and checked
// against the live company brand by eye before being committed here. See
// public/logos/hirers/ for the actual files.
export const HIRER_LOGO_IMAGES: Record<string, string> = {
  'Bajaj Finserv':       '/logos/hirers/bajaj-finserv.svg',
  'Capgemini':           '/logos/hirers/capgemini.svg',
  'Citibank':            '/logos/hirers/citi.svg',
  'Cognizant':           '/logos/hirers/cognizant.svg',
  'Deloitte':            '/logos/hirers/deloitte.svg',
  'EY':                  '/logos/hirers/ey.svg',
  'Edelman':             '/logos/hirers/edelman.gif',
  'Flipkart':            '/logos/hirers/flipkart.svg',
  'Genpact':             '/logos/hirers/genpact.svg',
  'HT Media':            '/logos/hirers/ht-media.svg',
  'Hindustan Times':     '/logos/hirers/ht-media.svg',
  'Hindustan Unilever':  '/logos/hirers/hindustan-unilever.svg',
  'IBM':                 '/logos/hirers/ibm.svg',
  'ITC':                 '/logos/hirers/itc.svg',
  'Infosys BPM':         '/logos/hirers/infosys-bpm.svg',
  'JP Morgan':           '/logos/hirers/jp-morgan.svg',
  'KPMG':                '/logos/hirers/kpmg.svg',
  'Kotak Mahindra':      '/logos/hirers/kotak-mahindra.svg',
  'Kotak Mahindra Bank': '/logos/hirers/kotak-mahindra.svg',
  'LTIMindtree':         '/logos/hirers/ltimindtree.svg',
  'Mphasis':             '/logos/hirers/mphasis.svg',
  'NDTV':                '/logos/hirers/ndtv.svg',
  'NITI Aayog':          '/logos/hirers/niti-aayog.svg',
  'News18':              '/logos/hirers/news18.png',
  'Ogilvy':              '/logos/hirers/ogilvy.svg',
  'Oracle':              '/logos/hirers/oracle.svg',
  'PayU':                '/logos/hirers/payu.svg',
  'PwC':                 '/logos/hirers/pwc.svg',
  'RBI':                 '/logos/hirers/rbi.svg',
  'Republic TV':         '/logos/hirers/republic-tv.svg',
  'Standard Chartered':  '/logos/hirers/standard-chartered.svg',
  'Tech Mahindra':       '/logos/hirers/tech-mahindra.svg',
  'The Hindu':           '/logos/hirers/the-hindu.svg',
  'Times Group':         '/logos/hirers/times-group.png',
  'Times of India':      '/logos/hirers/times-of-india.svg',
  'UPSC':                '/logos/hirers/upsc.png',
  'WNS':                 '/logos/hirers/wns.svg',
  'Weber Shandwick':     '/logos/hirers/weber-shandwick.jpg',
}
